### ISSUE TITLE
Veonim stops working after python script execution

### ISSUE THREAD

**Issue by whzup** [veonim/veonim#637] opened 2019-04-16 19:17 UTC
A minimal working example for this is the following python program:
```python
"""
print.py
"""

print(c)
```
execute this with `:!python3 %` and veonim doesn't respond to any input. This happens as soon as any error occurs during the the program execution. If there are no errors, it runs smoothly. It's quite sad that this happens since 0.22 isn't really usable for me because of the graphic bugs.

Veonim 0.14
Neovim 0.31
OS: OpenSUSE Leap 15

**Comment by breja** [comment] 2019-04-26 01:43
Are you saying that the python script runs smoothly if there are no errors caused by the python script?

I've actually never tried running python in veonim. I think Neovim requires installing a separate package for python support. I wonder if this factors into this in any way. (https://github.com/neovim/neovim/wiki/Installing-Neovim#opensuse)

I'll have to try for myself and see what happens.

**Comment by whzup** [comment] 2019-04-26 05:54
@breja Thanks for your answer.

I actually don't think it has something to do with Neovim not having the Python packages since I use the `!` which should execute the script in the shell and not as a part of Neovim, right?
By the way, this behaviour also occurs with `.tex` files (LaTeX). If I compile those veonim just stops responding (only Veonim commands like "change buffer" still work but the GUI doesn't respond at all). Maybe veonim can't handle the buffer change to the shell output?

My compilation bindings look like this:
```
autocmd FileType tex nno <F5> :!pdflatex %:p -output-format=pdf <CR>
autocmd FileType text nno <F5> :!python %:p
```
If I compile it in the Neovim shell `term://bash` it works perfectly.

In version 0.22 my bindings work though, so maybe it's a feature you freshly added?

**Comment by breja** [comment] 2019-05-07 21:44
In 0.22 veonim added `ext_messages` and `ext_multigrid` support from neovim. Before 0.22 windows and messages were a big hack. I think the shell output would have neovim send multi-line message events, and this didn't really work in <0.22.

If that's the case, then 0.14 won't be fixed since there are breaking changes between veonim <--> neovim API. I will check it out just to make sure, but otherwise I will be focusing on fixing the graphic glitches in master.

**Closed** 2020-05-21 23:38 UTC
Labels: INVESTIGATE
