### ISSUE TITLE
With Veonim rename, the new variable name length cannot exceed the original

### ISSUE THREAD

**Issue by bfulop** [veonim/veonim#415] opened 2018-07-12 08:57 UTC
Strange coding style rule, hidden in Veonim:

In plain JavaScript (haven't tried elsewhere),  ~~I can only rename a variable (`:Veonim rename`) to a max four letter word, but not more (`foo` is OK, but not `foobar`.)~~, with `:Veonim rename` the length of the new variable name cannot exceed that of the original variable. `foobar` can be renamed to `foobaz` but not to `foobarbaz`. 

If the new variable name is too long, the original variable name is left untouched, and new text is inserted somewhere further along on the line (e.g. parameter name is replaced when the target was the function name). 

I'm triggering the rename with `sr` or `:Veonim rename`, then edit the new name, then hit `esc`.

**Comment by breja** [comment] 2018-07-13 00:12
It's not a bug - it's a feature intended to help the developer keep variable names short and concise. 😜 

jk - i am looking into this

**Comment by breja** [comment] 2018-07-13 18:32
Thanks for the report. This should be fixed now.

**tech details**
the sent `textDocument/rename` line/col position was being sent *after* the rename operation. this position did not correspond with a valid position in the current buffer. the code was changed to cache the line/col position before `:Veonim rename` starts and send the cached position to the language server

**Closed** 2018-07-14 06:20 UTC
Labels: BUG
