### ISSUE TITLE
Statusline improvements?

### ISSUE THREAD

**Issue by clason** [veonim/veonim#565] opened 2019-01-02 10:32 UTC
I think this is by design, but I do miss the vim mode indicator in the status line (esp. insert vs. replace and visual vs. visual-block). 

Something I've also found useful is an indicator for the relative position in the file -- either as linenumber/total linenumber or X%.

(Alternatively, is it possible -- or feasible -- to disable the veonim status bar and use the standard status line with, e.g., airline?)

**Comment by breja** [comment] 2019-01-03 00:53
I do want to provide customization of the statusline - it's something I've thought about for some time. HTML/CSS/JavaScript allows unlimited customization and I think it would be neat to leverage that possibility. 

The issue is that I haven't figured out a good way to allow full customization without introducing a new API. I would prefer to have all veonim customization done via vimrc and writing HTML/CSS/JS in vimscript is maybe a new level of hell. With the vim statusline customization options it is limited to text/colors only and will make it difficult to parse/update the realtime values. Maybe the vscode API would be better as it allows specifying icons, but that would require writing full blown vscode extensions.

I'm not sure... will have to think more about this.

It is currently not possible to use the nvim statusline - I don't think neovim exposes this in the UI grid protocol. Maybe it's trivial and no one has asked, I don't know. 🤷‍♂️

**Comment by clason** [comment] 2019-01-03 09:57
> It is currently not possible to use the nvim statusline - I don't think neovim exposes this in the UI grid protocol. Maybe it's trivial and no one has asked, I don't know. 🤷‍♂️

Ah, that makes sense. (It's planned, at least: https://github.com/neovim/neovim/issues/9421)

Regarding customization, maybe an intermediate approach would be to define hard-coded "blocks" (status, git branch/status, encoding, filetype, line number, what have you) and then allow users to compose them via a vimL variable like 
```viml
let g:veonim_statusbar = "project | git branch status | filetype | linenumber"
```
?

**Comment by breja** [comment] 2019-01-05 04:42
I like the intermediate approach as it allows some degree of statusline customization until neovim supports `ext_statusline`. I will add this to the work queue.

**Comment by teto** [comment] 2019-01-10 02:11
ext_statusline has to be discussed but something akin to i3bar's protocol https://i3wm.org/docs/i3bar-protocol.html might work out well.

**Comment by breja** [comment] 2019-01-11 14:48
Interesting - I will take a look at the protocol. Thanks!

**Comment by breja** [comment] 2020-05-21 23:15
This is out of scope until Neovim supports externalized statusline

**Closed by breja** 2020-05-21 23:15 UTC
Labels: EXPLORE, IDK HARD
